version: "2"
services:
  sustainable-cities:
    command: "npm start"
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3000"
    restart: always
    container_name: backoffice
