const MAX_BMES_PER_PAGE = 5;
const MAX_IMPACTS_PER_PAGE = 5;

// image/file managemenet
const MAX_IMAGES_ACCEPTED = 1;
const MAX_SIZE_IMAGE = 1048576; // 1MB

export { MAX_BMES_PER_PAGE, MAX_IMPACTS_PER_PAGE, MAX_IMAGES_ACCEPTED, MAX_SIZE_IMAGE };
